### ISSUE TITLE
parsing responses fails sometimes on fullfillment node

### ISSUE THREAD

**Issue by alias** [api-ai/apiai-java-sdk#5] opened 2016-12-05 12:11 UTC
Response from an Intent without webhook:
...
```
"fulfillment": {                                    
	"speech": "Hallo.." 
	"messages": [{                              
		"type": 0,                          
		"speech": "Hallo.."
	}]                                          
}, 
```
...
With webhook enabled:        
...
```
fulfillment": {                                                                           
   	"speech": "Hallo..",              
   	"source": "oo",                           
   	"displayText": "Test",                   
   	"messages": {                             
   		"type": 0,                        
   		"speech": "Hallo..o"       
  	}
},
```
the gson parser seems to insist on the array of messages:

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 34 column 20 path $.result.fulfillment.messages
com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)

Or: the additonal "displayText" in the webhook response triggers that change.

**Comment by folomeev** [comment] 2016-12-05 13:11
According to the official documentation (https://docs.api.ai/docs/rich-messages) GSON parser is right. The "messages" field should be an array of messages (e.g. one element array in case of single message response).

May you provide more specific information the webhook response?

**Comment by alias** [comment] 2016-12-06 07:47
Acc. to https://docs.api.ai/docs/webhook you may provide also an additional text. In my case I returned speech and displayText (and also a source). I think api.ai should always respond with an array in the message node.

**Comment by folomeev** [comment] 2016-12-06 08:50
Thank you for information, the issue is confirmed. It  will be fixed on a server side in a closest future.
I'll notify you after.

**Comment by folomeev** [comment] 2016-12-06 13:47
Fix published.

**Closed by folomeev** 2016-12-06 13:47 UTC
